<a href="https://colab.research.google.com/github/PradeepChanvir/Simple_Python_Programs/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.Creating a 3x3 square matrix and computing its determinant.

Prompt: Python code creating 3x3 square matrix and computing its determinant using inputs given from user.

In [ ]:
import numpy as np

def get_matrix_input():
    print('Enter the elements of a 3x3 matrix row by row:')
    matrix = []
    for i in range(3):
        row = []
        for j in range(3):
            while True:
                try:
                    val = float(input(f'Element [{i+1}][{j+1}]: '))
                    row.append(val)
                    break
                except ValueError:
                    print('Invalid input. Please enter a number.')
        matrix.append(row)
    return np.array(matrix)

# Get matrix from user
user_matrix = get_matrix_input()

# Compute determinant
det = np.linalg.det(user_matrix)

print('\nYour Matrix:')
print(user_matrix)
print(f'\nDeterminant: {det:.2f}')

Enter the elements of a 3x3 matrix row by row:
Element [1][1]: 8
Element [1][2]: 5
Element [1][3]: 4
Element [2][1]: 6
Element [2][2]: 3
Element [2][3]: 2
Element [3][1]: 7
Element [3][2]: 8
Element [3][3]: 1

Your Matrix:
[[8. 5. 4.]
 [6. 3. 2.]
 [7. 8. 1.]]

Determinant: 44.00


 Creating a 3x3 square matrix and computing its determinant **without** `numpy`.


Prompt: Python code creating 3x3 square matrix and computing its determinant using inputs given from user, without using numpy.


In [2]:
def get_matrix_input_no_numpy():
    print('Enter the elements of a 3x3 matrix row by row:')
    matrix = []
    for i in range(3):
        row = []
        for j in range(3):
            while True:
                try:
                    val = float(input(f'Element [{i+1}][{j+1}]: '))
                    row.append(val)
                    break
                except ValueError:
                    print('Invalid input. Please enter a number.')
        matrix.append(row)
    return matrix

def calculate_determinant_3x3(matrix):
    # For a 3x3 matrix [[a, b, c], [d, e, f], [g, h, i]]
    # Determinant = a(ei - fh) - b(di - fg) + c(dh - eg)
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]

    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    return det

# Get matrix from user
user_matrix_no_numpy = get_matrix_input_no_numpy()

# Compute determinant
det_no_numpy = calculate_determinant_3x3(user_matrix_no_numpy)

print('\nYour Matrix:')
for row in user_matrix_no_numpy:
    print(row)
print(f'\nDeterminant: {det_no_numpy:.2f}')


Enter the elements of a 3x3 matrix row by row:
Element [1][1]: 5
Element [1][2]: 8
Element [1][3]: 3
Element [2][1]: 9
Element [2][2]: 2
Element [2][3]: 6
Element [3][1]: 7
Element [3][2]: 1
Element [3][3]: 8

Your Matrix:
[5.0, 8.0, 3.0]
[9.0, 2.0, 6.0]
[7.0, 1.0, 8.0]

Determinant: -205.00


## 2. Finding the inverse of a 3x3 matrix from user input

Prompt: Python code for finding inverse of a 3x3 matrix and take inputs from the user.

In [ ]:
import numpy as np

def get_3x3_input():
    print('Enter the elements for a 3x3 matrix:')
    elements = []
    for i in range(3):
        row = []
        for j in range(3):
            while True:
                try:
                    val = float(input(f'Element [{i+1}][{j+1}]: '))
                    row.append(val)
                    break
                except ValueError:
                    print('Please enter a valid number.')
        elements.append(row)
    return np.array(elements)

# Get input
mat = get_3x3_input()

try:
    # Calculate Inverse
    inv_mat = np.linalg.inv(mat)
    print('\nOriginal Matrix:')
    print(mat)
    print('\nInverse Matrix:')
    print(inv_mat)
except np.linalg.LinAlgError:
    print('\nThis matrix is singular and does not have an inverse (determinant is 0).')

Enter the elements for a 3x3 matrix:
Element [1][1]: 1
Element [1][2]: 2
Element [1][3]: 3
Element [2][1]: 0
Element [2][2]: 1
Element [2][3]: 4
Element [3][1]: 5
Element [3][2]: 6
Element [3][3]: 0

Original Matrix:
[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]

Inverse Matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


##  Finding the inverse of a 3x3 matrix from user input (without numpy)


Prompt: Python code for finding inverse of a 3x3 matrix and take inputs from the user, without using numpy.


In [3]:
def get_matrix_input_no_numpy():
    print('Enter the elements of a 3x3 matrix row by row:')
    matrix = []
    for i in range(3):
        row = []
        for j in range(3):
            while True:
                try:
                    val = float(input(f'Element [{i+1}][{j+1}]: '))
                    row.append(val)
                    break
                except ValueError:
                    print('Invalid input. Please enter a number.')
        matrix.append(row)
    return matrix

def calculate_determinant_3x3_no_numpy(matrix):
    # For a 3x3 matrix [[a, b, c], [d, e, f], [g, h, i]]
    # Determinant = a(ei - fh) - b(di - fg) + c(dh - eg)
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]

    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    return det

def get_minor(matrix, i, j):
    return [row[:j] + row[j+1:] for row in (matrix[:i] + matrix[i+1:])]

def get_determinant_2x2(matrix):
    return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

def calculate_inverse_3x3_no_numpy(matrix):
    determinant = calculate_determinant_3x3_no_numpy(matrix)

    if determinant == 0:
        return None  # Matrix is singular, inverse does not exist

    cofactors = []
    for r in range(3):
        cofactor_row = []
        for c in range(3):
            minor = get_minor(matrix, r, c)
            det_minor = get_determinant_2x2(minor)
            # Apply checkerboard pattern for sign
            cofactor_val = ((-1)**(r+c)) * det_minor
            cofactor_row.append(cofactor_val)
        cofactors.append(cofactor_row)

    # Transpose the cofactor matrix to get the adjugate matrix
    adjugate = [[cofactors[j][i] for j in range(3)] for i in range(3)]

    # Divide adjugate by determinant to get the inverse
    inverse = [[element / determinant for element in row] for row in adjugate]

    return inverse

# Get matrix from user
user_matrix = get_matrix_input_no_numpy()

print('\nYour Matrix:')
for row in user_matrix:
    print(row)

inverse_matrix = calculate_inverse_3x3_no_numpy(user_matrix)

if inverse_matrix is None:
    print('\nThis matrix is singular and does not have an inverse (determinant is 0).')
else:
    print('\nInverse Matrix:')
    for row in inverse_matrix:
        print([f'{val:.4f}' for val in row]) # Print with 4 decimal places for readability


Enter the elements of a 3x3 matrix row by row:
Element [1][1]: 6
Element [1][2]: 8
Element [1][3]: 4
Element [2][1]: 9
Element [2][2]: 7
Element [2][3]: 2
Element [3][1]: 1
Element [3][2]: 6
Element [3][3]: 5

Your Matrix:
[6.0, 8.0, 4.0]
[9.0, 7.0, 2.0]
[1.0, 6.0, 5.0]

Inverse Matrix:
['-1.2778', '0.8889', '0.6667']
['2.3889', '-1.4444', '-1.3333']
['-2.6111', '1.5556', '1.6667']


## 3. Solving a system of linear equations
We are solving:
1.  $2x + 3y = 10$
2.  $4x + 5y = 20$

In [ ]:
import numpy as np

# Coefficients matrix (A)
A = np.array([[2, 3], [4, 5]])

# Constants vector (b)
b = np.array([10, 20])

# Solve for x and y
try:
    solution = np.linalg.solve(A, b)
    x, y = solution
    print(f'Solution:\nx = {x}\ny = {y}')
except np.linalg.LinAlgError:
    print('The system cannot be solved (singular matrix).')

Solution:
x = 5.0
y = 0.0


## Solving a system of linear equations (without numpy)
We are solving:
1.  $a_1x + b_1y = c_1$
2.  $a_2x + b_2y = c_2$

Prompt: Python code for solving a system of two linear equations, taking inputs from the user, and without using numpy.

In [4]:
def solve_2x2_linear_system_no_numpy():
    print('Enter coefficients for the first equation (a1x + b1y = c1):')
    while True:
        try:
            a1 = float(input('Enter a1: '))
            b1 = float(input('Enter b1: '))
            c1 = float(input('Enter c1: '))
            break
        except ValueError:
            print('Invalid input. Please enter a number.')

    print('\nEnter coefficients for the second equation (a2x + b2y = c2):')
    while True:
        try:
            a2 = float(input('Enter a2: '))
            b2 = float(input('Enter b2: '))
            c2 = float(input('Enter c2: '))
            break
        except ValueError:
            print('Invalid input. Please enter a number.')

    # Calculate the determinant of the coefficient matrix
    determinant = a1 * b2 - a2 * b1

    if determinant == 0:
        # Check for consistency (no solution or infinitely many solutions)
        # If (c1*b2 - c2*b1 == 0) and (a1*c2 - a2*c1 == 0), then infinitely many solutions
        # Otherwise, no solution
        if (c1 * b2 - c2 * b1 == 0) and (a1 * c2 - a2 * c1 == 0):
            print('\nInfinitely many solutions.')
        else:
            print('\nNo unique solution (lines are parallel or coincident).')
        return None, None
    else:
        # Calculate x and y using Cramer's rule
        x = (c1 * b2 - c2 * b1) / determinant
        y = (a1 * c2 - a2 * c1) / determinant
        return x, y

x_solution, y_solution = solve_2x2_linear_system_no_numpy()

if x_solution is not None and y_solution is not None:
    print(f'\nSolution:\nx = {x_solution:.2f}\ny = {y_solution:.2f}')


Enter coefficients for the first equation (a1x + b1y = c1):
Enter a1: 7
Enter b1: 8
Enter c1: 4

Enter coefficients for the second equation (a2x + b2y = c2):
Enter a2: 9
Enter b2: 2
Enter c2: 3

Solution:
x = 0.28
y = 0.26
