<a href="https://colab.research.google.com/github/PradeepChanvir/Simple_Python_Programs/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.Creating a 3x3 square matrix and computing its determinant.

Prompt: Python code creating 3x3 square matrix and computing its determinant using inputs given from user.

In [7]:
import numpy as np

def get_matrix_input():
    print('Enter the elements of a 3x3 matrix row by row:')
    matrix = []
    for i in range(3):
        row = []
        for j in range(3):
            while True:
                try:
                    val = float(input(f'Element [{i+1}][{j+1}]: '))
                    row.append(val)
                    break
                except ValueError:
                    print('Invalid input. Please enter a number.')
        matrix.append(row)
    return np.array(matrix)

# Get matrix from user
user_matrix = get_matrix_input()

# Compute determinant
det = np.linalg.det(user_matrix)

print('\nYour Matrix:')
print(user_matrix)
print(f'\nDeterminant: {det:.2f}')

Enter the elements of a 3x3 matrix row by row:
Element [1][1]: 8
Element [1][2]: 5
Element [1][3]: 4
Element [2][1]: 6
Element [2][2]: 3
Element [2][3]: 2
Element [3][1]: 7
Element [3][2]: 8
Element [3][3]: 1

Your Matrix:
[[8. 5. 4.]
 [6. 3. 2.]
 [7. 8. 1.]]

Determinant: 44.00


## 2. Finding the inverse of a 3x3 matrix from user input

Prompt: Python code for finding inverse of a 3x3 matrix and take inputs from the user.

In [15]:
import numpy as np

def get_3x3_input():
    print('Enter the elements for a 3x3 matrix:')
    elements = []
    for i in range(3):
        row = []
        for j in range(3):
            while True:
                try:
                    val = float(input(f'Element [{i+1}][{j+1}]: '))
                    row.append(val)
                    break
                except ValueError:
                    print('Please enter a valid number.')
        elements.append(row)
    return np.array(elements)

# Get input
mat = get_3x3_input()

try:
    # Calculate Inverse
    inv_mat = np.linalg.inv(mat)
    print('\nOriginal Matrix:')
    print(mat)
    print('\nInverse Matrix:')
    print(inv_mat)
except np.linalg.LinAlgError:
    print('\nThis matrix is singular and does not have an inverse (determinant is 0).')

Enter the elements for a 3x3 matrix:
Element [1][1]: 1
Element [1][2]: 2
Element [1][3]: 3
Element [2][1]: 0
Element [2][2]: 1
Element [2][3]: 4
Element [3][1]: 5
Element [3][2]: 6
Element [3][3]: 0

Original Matrix:
[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]

Inverse Matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


## 3. Solving a system of linear equations
We are solving:
1.  $2x + 3y = 10$
2.  $4x + 5y = 20$

In [16]:
import numpy as np

# Coefficients matrix (A)
A = np.array([[2, 3], [4, 5]])

# Constants vector (b)
b = np.array([10, 20])

# Solve for x and y
try:
    solution = np.linalg.solve(A, b)
    x, y = solution
    print(f'Solution:\nx = {x}\ny = {y}')
except np.linalg.LinAlgError:
    print('The system cannot be solved (singular matrix).')

Solution:
x = 5.0
y = 0.0
